Homepage
blackmeat/simple-twitter-express-starter pull request #12
Opened 2020-03-11 09:41 UTC by tonyfang1992

twitter首頁
1.能夠推送tweet並重新導向首頁
2.下方依照建立時間遠近，列出所有tweet
3.右方依照不同的使用者follow數列出10名最受歡迎推主
完成以下路由
GET / 轉向 /tweets
GET /tweets 看見站內所有的推播，以及跟隨者最多的使用者 (設為前台首頁)
POST /tweets 將新增的推播寫入資料庫
POST /followships/:followingId 新增一筆 followship 記錄
DELETE /followships/:followingId 刪除一筆 followship 記錄

需安裝以下
moment
multer
imgur-node-api
bcryptjs

追加like unlike功能

2020-03-11 14:46 UTC, blackmeat commented
對了！怎麼沒有上傳package.json檔案，如果要安裝的話，你應該也是另外安裝，照理說應該我merge之後package.json就會出現你另外安裝的套件，我只要直接執行npm install就好（疑？

2020-03-12 04:05 UTC, blackmeat requested changes

2020-03-12 04:05 UTC, blackmeat commented on controllers/userController.js
> +    } else {
這裡也需要修改，同一個部分~

2020-03-12 04:05 UTC, blackmeat commented on controllers/userController.js
> +    } else {
相同部分

2020-03-12 04:05 UTC, blackmeat commented on controllers/tweetController.js
> +
這邊User要找出追蹤人數排名前10名
一開始就limit這樣只有找出10位使用者比較 這十位搞不好都是追蹤者0的 然後第十一位是3 這樣後面排序也顯示不到這個第十一位，因為就只有一開始抓出來的10個比較
所以應該是全部排序完 再抓前10筆資料

2020-03-12 04:05 UTC, blackmeat commented on controllers/tweetController.js
> +
可以用slice()

2020-03-12 05:03 UTC, tonyfang1992 commented on controllers/tweetController.js
> +
對的，的確資料只撈了10筆下來，來修改~

2020-03-12 05:05 UTC, tonyfang1992 commented on controllers/userController.js
> +    } else {
了解!

2020-03-12 05:05 UTC, tonyfang1992 commented on controllers/userController.js
> +    } else {
了解!

2020-03-12 05:16 UTC, tonyfang1992 commented
wait for update...

2020-03-12 06:54 UTC, blackmeat requested changes

2020-03-12 06:54 UTC, blackmeat commented on controllers/tweetController.js
> +      .then((restaurant) => {
這裡面的參數應該是like xDD

2020-03-12 06:54 UTC, blackmeat commented on controllers/tweetController.js
> +        tweet.destroy()
這上面應該也是like 然後like.destroy()

2020-03-12 07:10 UTC, tonyfang1992 commented on controllers/tweetController.js
> +      .then((restaurant) => {
XDDD

2020-03-12 07:10 UTC, tonyfang1992 commented on controllers/tweetController.js
> +        tweet.destroy()
對的!

2020-03-12 07:21 UTC, blackmeat approved these changes

2020-03-12 11:40 UTC, merged